#!/bin/bash
set -e

# Create User and Database
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	    CREATE USER $PROJECT_DB_USER WITH PASSWORD '$PROJECT_DB_PASSWORD';
	    CREATE DATABASE $PROJECT_DB_NAME;
	    GRANT ALL PRIVILEGES ON DATABASE $PROJECT_DB_NAME TO $PROJECT_DB_USER;
EOSQL
